import { getAmplifyDataClientConfig } from "@aws-amplify/backend/function/runtime";
import { Amplify } from "aws-amplify";
import { generateClient } from "aws-amplify/data";
import type { AppSyncResolverEvent } from "aws-lambda";

// `$amplify/env/*` is generated by `ampx` at deploy time; a checked-in
// placeholder under .amplify/generated keeps a fresh clone typechecking.
import { env } from "$amplify/env/audit-writer";

import { activeClient } from "../../../config";
import type { Schema } from "../../data/resource";
import { writeAuditEvent } from "../shared/audit";
import { resolveCaller, UnauthenticatedError } from "../shared/identity";

/**
 * Actions a user may record about their own activity.
 *
 * Administrative actions are deliberately absent: those are written by the
 * admin functions from inside the operation they describe, so a user cannot
 * call this mutation to fabricate a "USER_CREATED" entry against someone else.
 */
const CLIENT_RECORDABLE_ACTIONS = new Set([
  "FILE_LIST",
  "FILE_DOWNLOAD",
  "FILE_UPLOAD",
  "FILE_UPLOAD_REJECTED_COLLISION",
  "ACCESS_DENIED",
]);

type Arguments = {
  action: string;
  outcome: string;
  bucketId?: string | null;
  objectKey?: string | null;
  detail?: unknown;
};

const { resourceConfig, libraryOptions } = await getAmplifyDataClientConfig(env);
Amplify.configure(resourceConfig, libraryOptions);
const client = generateClient<Schema>();

export const handler = async (
  event: AppSyncResolverEvent<Arguments>,
): Promise<boolean> => {
  let caller;
  try {
    caller = resolveCaller(event);
  } catch (error) {
    if (error instanceof UnauthenticatedError) {
      // AppSync should never route an unauthenticated request here, since the
      // mutation requires `allow.authenticated()`. Treat it as a hard error.
      console.error("AUDIT_UNAUTHENTICATED", { error: error.message });
      throw error;
    }
    throw error;
  }

  const { action, outcome, bucketId, objectKey, detail } = event.arguments;

  if (!CLIENT_RECORDABLE_ACTIONS.has(action)) {
    // Refusing is itself worth recording: someone reached past the UI to call
    // this mutation with an action it does not offer.
    console.warn("AUDIT_ACTION_REJECTED", { action, actorSub: caller.sub });
    await writeAuditEvent(client, activeClient.clientId, caller, {
      action: "ACCESS_DENIED",
      outcome: "DENIED",
      detail: {
        reason: "action-not-client-recordable",
        attemptedAction: action,
      },
    });
    throw new Error(`Action "${action}" cannot be recorded by a client.`);
  }

  const validatedBucketId =
    bucketId && activeClient.buckets.some((b) => b.id === bucketId)
      ? bucketId
      : null;

  if (bucketId && !validatedBucketId) {
    console.warn("AUDIT_UNKNOWN_BUCKET", { bucketId, actorSub: caller.sub });
  }

  await writeAuditEvent(client, activeClient.clientId, caller, {
    action: action as Schema["AuditEvent"]["type"]["action"],
    outcome: outcome as Schema["AuditEvent"]["type"]["outcome"],
    bucketId: validatedBucketId,
    objectKey: objectKey ?? null,
    detail: detail ?? null,
  });

  return true;
};
