import {
  AdminAddUserToGroupCommand,
  AdminCreateUserCommand,
  AdminDisableUserCommand,
  AdminEnableUserCommand,
  AdminListGroupsForUserCommand,
  AdminRemoveUserFromGroupCommand,
  AdminUserGlobalSignOutCommand,
  CognitoIdentityProviderClient,
  ListUsersCommand,
  ListUsersInGroupCommand,
  type UserType,
} from "@aws-sdk/client-cognito-identity-provider";
import { getAmplifyDataClientConfig } from "@aws-amplify/backend/function/runtime";
import { Amplify } from "aws-amplify";
import { generateClient } from "aws-amplify/data";
import type { AppSyncResolverEvent } from "aws-lambda";

// `$amplify/env/*` is generated by `ampx` at deploy time; a checked-in
// placeholder under .amplify/generated keeps a fresh clone typechecking.
import { env } from "$amplify/env/admin-users";

import { activeClient } from "../../../config";
import type { Schema } from "../../data/resource";
import { writeAuditEvent } from "../shared/audit";
import { resolveCaller } from "../shared/identity";
import {
  ADMIN_GROUP,
  assertAdminSafety,
  OperationError,
  parseOperation,
  type PortalUser,
  type UserStatus,
} from "./operations";

const { resourceConfig, libraryOptions } = await getAmplifyDataClientConfig(env);
Amplify.configure(resourceConfig, libraryOptions);

const data = generateClient<Schema>();
const cognito = new CognitoIdentityProviderClient();
const USER_POOL_ID = env.AMPLIFY_AUTH_USERPOOL_ID;

export const handler = async (
  event: AppSyncResolverEvent<{ operation: string; payload: unknown }>,
): Promise<unknown> => {
  const caller = resolveCaller(event);

  // AppSync already enforces the admin group on this mutation. Re-checking
  // here means the handler is still safe if that binding is ever loosened, and
  // it gives us an audit record of the attempt rather than a silent 401.
  if (!caller.groups.includes(ADMIN_GROUP)) {
    await writeAuditEvent(data, activeClient.clientId, caller, {
      action: "ACCESS_DENIED",
      outcome: "DENIED",
      detail: { reason: "not-an-admin", mutation: "manageUsers" },
    });
    throw new Error("Administrator access is required.");
  }

  const request = parseOperation(event.arguments.operation, event.arguments.payload);

  try {
    switch (request.operation) {
      case "listUsers":
        return await listUsers();

      case "createUser":
        return await createUser(request, caller);

      case "disableUser":
        return await disableUser(request.username, caller);

      case "enableUser":
        return await enableUser(request.username, caller);

      case "setUserGroups":
        return await setUserGroups(request.username, request.groups, caller);

      case "resendInvite":
        return await resendInvite(request.username, caller);
    }
  } catch (error) {
    if (error instanceof OperationError) {
      // Expected, admin-facing refusal (e.g. last-admin protection). Record it
      // and surface the message, which is written to be shown in the UI.
      await writeAuditEvent(data, activeClient.clientId, caller, {
        action: "ACCESS_DENIED",
        outcome: "DENIED",
        detail: {
          operation: event.arguments.operation,
          reason: error.message,
        },
      });
      throw new Error(error.message);
    }

    console.error("ADMIN_USERS_FAILED", {
      operation: event.arguments.operation,
      actorSub: caller.sub,
      error,
    });
    // Do not leak AWS error detail to the browser.
    throw new Error(
      `The operation could not be completed. The error has been logged.`,
    );
  }
};

/* -------------------------------------------------------------------------- */
/* Operations                                                                  */
/* -------------------------------------------------------------------------- */

async function listUsers(): Promise<PortalUser[]> {
  const users = await listAllCognitoUsers();
  const lastLogins = await fetchLastLogins();

  const withGroups = await Promise.all(
    users.map(async (user) => {
      const groups = await listGroupsForUser(user.Username!);
      return toPortalUser(user, groups, lastLogins);
    }),
  );

  // Enabled users first, then alphabetically — the list is a working tool for
  // an admin, and disabled accounts are the ones they least often need.
  return withGroups.sort((a, b) => {
    if (a.enabled !== b.enabled) return a.enabled ? -1 : 1;
    return a.email.localeCompare(b.email);
  });
}

async function createUser(
  request: Extract<ReturnType<typeof parseOperation>, { operation: "createUser" }>,
  caller: ReturnType<typeof resolveCaller>,
) {
  const created = await cognito.send(
    new AdminCreateUserCommand({
      UserPoolId: USER_POOL_ID,
      Username: request.email,
      UserAttributes: [
        { Name: "email", Value: request.email },
        { Name: "email_verified", Value: "true" },
        { Name: "given_name", Value: request.givenName },
        { Name: "family_name", Value: request.familyName },
      ],
      // Cognito emails the temporary password. The user is forced to change it
      // and enrol in TOTP on first sign-in.
      DesiredDeliveryMediums: ["EMAIL"],
    }),
  );

  const username = created.User?.Username;
  if (!username) {
    throw new Error("Cognito did not return a username for the created user.");
  }

  for (const group of request.groups) {
    await cognito.send(
      new AdminAddUserToGroupCommand({
        UserPoolId: USER_POOL_ID,
        Username: username,
        GroupName: group,
      }),
    );
  }

  await writeAuditEvent(data, activeClient.clientId, caller, {
    action: "USER_CREATED",
    outcome: "SUCCESS",
    targetUser: username,
    detail: { email: request.email, groups: request.groups },
  });

  const groups = await listGroupsForUser(username);
  return toPortalUser(created.User!, groups, new Map());
}

async function disableUser(username: string, caller: ReturnType<typeof resolveCaller>) {
  assertAdminSafety(
    { targetUsername: username, kind: "disable" },
    caller.username,
    await listEnabledAdminUsernames(),
  );

  await cognito.send(
    new AdminDisableUserCommand({ UserPoolId: USER_POOL_ID, Username: username }),
  );

  // Disabling alone leaves existing tokens valid until they expire. Global
  // sign-out revokes them, so offboarding takes effect immediately rather than
  // up to an access token's lifetime later.
  await cognito.send(
    new AdminUserGlobalSignOutCommand({
      UserPoolId: USER_POOL_ID,
      Username: username,
    }),
  );

  await writeAuditEvent(data, activeClient.clientId, caller, {
    action: "USER_DISABLED",
    outcome: "SUCCESS",
    targetUser: username,
    detail: { sessionsRevoked: true },
  });

  return { username, enabled: false };
}

async function enableUser(username: string, caller: ReturnType<typeof resolveCaller>) {
  await cognito.send(
    new AdminEnableUserCommand({ UserPoolId: USER_POOL_ID, Username: username }),
  );

  await writeAuditEvent(data, activeClient.clientId, caller, {
    action: "USER_REENABLED",
    outcome: "SUCCESS",
    targetUser: username,
  });

  return { username, enabled: true };
}

async function setUserGroups(
  username: string,
  nextGroups: readonly string[],
  caller: ReturnType<typeof resolveCaller>,
) {
  const current = await listGroupsForUser(username);

  assertAdminSafety(
    { targetUsername: username, kind: "setGroups", nextGroups },
    caller.username,
    await listEnabledAdminUsernames(),
  );

  const toAdd = nextGroups.filter((g) => !current.includes(g));
  const toRemove = current.filter((g) => !nextGroups.includes(g));

  for (const group of toAdd) {
    await cognito.send(
      new AdminAddUserToGroupCommand({
        UserPoolId: USER_POOL_ID,
        Username: username,
        GroupName: group,
      }),
    );
  }

  for (const group of toRemove) {
    await cognito.send(
      new AdminRemoveUserFromGroupCommand({
        UserPoolId: USER_POOL_ID,
        Username: username,
        GroupName: group,
      }),
    );
  }

  // A user whose groups changed is carrying a token that still asserts the old
  // ones. Revoking forces a fresh token on next request, so a removed grant
  // stops applying immediately.
  if (toRemove.length > 0) {
    await cognito.send(
      new AdminUserGlobalSignOutCommand({
        UserPoolId: USER_POOL_ID,
        Username: username,
      }),
    );
  }

  await writeAuditEvent(data, activeClient.clientId, caller, {
    action: "USER_GROUPS_CHANGED",
    outcome: "SUCCESS",
    targetUser: username,
    detail: {
      previous: current,
      next: nextGroups,
      added: toAdd,
      removed: toRemove,
      sessionsRevoked: toRemove.length > 0,
    },
  });

  return { username, groups: nextGroups };
}

async function resendInvite(username: string, caller: ReturnType<typeof resolveCaller>) {
  await cognito.send(
    new AdminCreateUserCommand({
      UserPoolId: USER_POOL_ID,
      Username: username,
      MessageAction: "RESEND",
      DesiredDeliveryMediums: ["EMAIL"],
    }),
  );

  await writeAuditEvent(data, activeClient.clientId, caller, {
    action: "USER_INVITE_RESENT",
    outcome: "SUCCESS",
    targetUser: username,
  });

  return { username, invitationResent: true };
}

/* -------------------------------------------------------------------------- */
/* Cognito helpers                                                             */
/* -------------------------------------------------------------------------- */

async function listAllCognitoUsers(): Promise<UserType[]> {
  const users: UserType[] = [];
  let paginationToken: string | undefined;

  do {
    const page = await cognito.send(
      new ListUsersCommand({
        UserPoolId: USER_POOL_ID,
        Limit: 60,
        PaginationToken: paginationToken,
      }),
    );
    users.push(...(page.Users ?? []));
    paginationToken = page.PaginationToken;
  } while (paginationToken);

  return users;
}

async function listGroupsForUser(username: string): Promise<string[]> {
  const groups: string[] = [];
  let nextToken: string | undefined;

  do {
    const page = await cognito.send(
      new AdminListGroupsForUserCommand({
        UserPoolId: USER_POOL_ID,
        Username: username,
        Limit: 60,
        NextToken: nextToken,
      }),
    );
    groups.push(...(page.Groups ?? []).map((g) => g.GroupName!).filter(Boolean));
    nextToken = page.NextToken;
  } while (nextToken);

  return groups;
}

/** Usernames of admins who could actually sign in — disabled ones cannot. */
async function listEnabledAdminUsernames(): Promise<string[]> {
  const admins: string[] = [];
  let nextToken: string | undefined;

  do {
    const page = await cognito.send(
      new ListUsersInGroupCommand({
        UserPoolId: USER_POOL_ID,
        GroupName: ADMIN_GROUP,
        Limit: 60,
        NextToken: nextToken,
      }),
    );
    for (const user of page.Users ?? []) {
      if (user.Enabled && user.Username) admins.push(user.Username);
    }
    nextToken = page.NextToken;
  } while (nextToken);

  return admins;
}

/* -------------------------------------------------------------------------- */
/* Mapping                                                                     */
/* -------------------------------------------------------------------------- */

/** Last login per Cognito sub, from the profile records the auth trigger maintains. */
async function fetchLastLogins(): Promise<Map<string, string>> {
  const logins = new Map<string, string>();
  let nextToken: string | null | undefined;

  do {
    const page = await data.models.UserProfile.list({
      limit: 200,
      nextToken: nextToken ?? undefined,
    });
    for (const profile of page.data ?? []) {
      if (profile.sub && profile.lastLoginAt) {
        logins.set(profile.sub, profile.lastLoginAt);
      }
    }
    nextToken = page.nextToken;
  } while (nextToken);

  return logins;
}

function attr(user: UserType, name: string): string {
  return user.Attributes?.find((a) => a.Name === name)?.Value ?? "";
}

function toPortalUser(
  user: UserType,
  groups: readonly string[],
  lastLogins: ReadonlyMap<string, string>,
): PortalUser {
  const sub = attr(user, "sub");
  return {
    username: user.Username ?? "",
    sub,
    email: attr(user, "email"),
    givenName: attr(user, "given_name"),
    familyName: attr(user, "family_name"),
    enabled: user.Enabled ?? false,
    status: normaliseStatus(user.UserStatus),
    groups: [...groups],
    createdAt: user.UserCreateDate?.toISOString() ?? "",
    lastLoginAt: lastLogins.get(sub) ?? null,
  };
}

function normaliseStatus(status: string | undefined): UserStatus {
  switch (status) {
    case "CONFIRMED":
    case "FORCE_CHANGE_PASSWORD":
    case "RESET_REQUIRED":
    case "UNCONFIRMED":
      return status;
    default:
      return "UNKNOWN";
  }
}
