import { getAmplifyDataClientConfig } from "@aws-amplify/backend/function/runtime";
import { Amplify } from "aws-amplify";
import { generateClient } from "aws-amplify/data";
import type { PostAuthenticationTriggerHandler } from "aws-lambda";

// `$amplify/env/*` is generated by `ampx` at deploy time; a checked-in
// placeholder under .amplify/generated keeps a fresh clone typechecking.
import { env } from "$amplify/env/post-authentication";

import { activeClient } from "../../../config";
import type { Schema } from "../../data/resource";
import { writeAuditEvent } from "../shared/audit";
import type { Caller } from "../shared/identity";

const { resourceConfig, libraryOptions } = await getAmplifyDataClientConfig(env);
Amplify.configure(resourceConfig, libraryOptions);
const data = generateClient<Schema>();

export const handler: PostAuthenticationTriggerHandler = async (event) => {
  const sub = event.request.userAttributes.sub;
  const email = event.request.userAttributes.email ?? "";
  const caller: Caller = {
    sub,
    username: event.userName,
    email,
    // The post-authentication event does not carry group membership — only the
    // pre-token-generation trigger does. Rather than spend an
    // AdminListGroupsForUser call inside every sign-in's critical path, LOGIN
    // records an empty group list. Membership at any point in time is
    // recoverable from the USER_GROUPS_CHANGED entries, which do record it.
    groups: [],
    sourceIp: event.request.clientMetadata?.["sourceIp"],
    userAgent: event.request.clientMetadata?.["userAgent"],
  };

  // A failure here must never block a sign-in. The user has already
  // authenticated successfully at this point; throwing would deny them access
  // because of a logging problem. Failures are logged loudly for CloudWatch
  // alarms instead — see docs/audit-coverage.md for the monitoring note.
  try {
    await writeAuditEvent(data, activeClient.clientId, caller, {
      action: "LOGIN",
      outcome: "SUCCESS",
      detail: {
        triggerSource: event.triggerSource,
        clientId: event.callerContext?.clientId,
      },
    });
  } catch (error) {
    console.error("POST_AUTH_AUDIT_FAILED", { sub, error });
  }

  try {
    await upsertProfile(sub, email);
  } catch (error) {
    console.error("POST_AUTH_PROFILE_FAILED", { sub, error });
  }

  return event;
};

/**
 * Upserts the profile without a conditional write.
 *
 * `loginCount` is read-then-written, so two sign-ins racing each other can lose
 * a count. That is acceptable: the field exists to spot dormant accounts, and
 * the audit log — which is append-only and never races — remains the
 * authoritative record of every individual login.
 */
async function upsertProfile(sub: string, email: string): Promise<void> {
  const now = new Date().toISOString();
  const existing = await data.models.UserProfile.get({ sub });

  if (existing.data) {
    await data.models.UserProfile.update({
      sub,
      email,
      lastLoginAt: now,
      loginCount: (existing.data.loginCount ?? 0) + 1,
    });
    return;
  }

  await data.models.UserProfile.create({
    sub,
    email,
    lastLoginAt: now,
    loginCount: 1,
  });
}
