import { getAmplifyDataClientConfig } from "@aws-amplify/backend/function/runtime";
import {
  CognitoIdentityProviderClient,
  ListUsersInGroupCommand,
} from "@aws-sdk/client-cognito-identity-provider";
import {
  DeleteRolePolicyCommand,
  GetRolePolicyCommand,
  IAMClient,
  PutRolePolicyCommand,
} from "@aws-sdk/client-iam";
import { Amplify } from "aws-amplify";
import { generateClient } from "aws-amplify/data";
import type { AppSyncResolverEvent } from "aws-lambda";

// `$amplify/env/*` is generated by `ampx` at deploy time; a checked-in
// placeholder under .amplify/generated keeps a fresh clone typechecking.
import { env } from "$amplify/env/admin-groups";

import { activeClient } from "../../../config/index";
import { grantedBuckets } from "../../../config/access";
import type { AccessMode } from "../../../config/types";
import type { Schema } from "../../data/resource";
import { buildBucketPolicy } from "../../shared/bucket-policy";
import { withEmail } from "../shared/actor-email";
import { writeAuditEvent } from "../shared/audit";
import { resolveCaller } from "../shared/identity";
import {
  type GroupAccessView,
  MANAGED_POLICY_NAME,
  OperationError,
  parseOperation,
} from "./operations";

const { resourceConfig, libraryOptions } = await getAmplifyDataClientConfig(env);
Amplify.configure(resourceConfig, libraryOptions);

const data = generateClient<Schema>();
const iam = new IAMClient();
const cognito = new CognitoIdentityProviderClient();

const ADMIN_GROUP = activeClient.groups.find((g) => g.isAdmin)!.id;
const ROLE_NAMES: Record<string, string> = JSON.parse(env.PORTAL_GROUP_ROLE_NAMES);
const USER_POOL_ID = env.AMPLIFY_AUTH_USERPOOL_ID;

export const handler = async (
  event: AppSyncResolverEvent<{ operation: string; payload: unknown }>,
): Promise<unknown> => {
  const caller = await withEmail(resolveCaller(event), USER_POOL_ID);

  if (!caller.groups.includes(ADMIN_GROUP)) {
    await writeAuditEvent(data, activeClient.clientId, caller, {
      action: "ACCESS_DENIED",
      outcome: "DENIED",
      detail: { reason: "not-an-admin", mutation: "manageGroups" },
    });
    throw new Error("Administrator access is required.");
  }

  try {
    const request = parseOperation(event.arguments.operation, event.arguments.payload);

    switch (request.operation) {
      case "listGroups":
        return await listGroups(caller);
      case "setGroupAccess":
        return await setGroupAccess(request.groupId, request.access, caller);
    }
  } catch (error) {
    if (error instanceof OperationError) {
      await writeAuditEvent(data, activeClient.clientId, caller, {
        action: "ACCESS_DENIED",
        outcome: "DENIED",
        detail: { operation: event.arguments.operation, reason: error.message },
      });
      throw new Error(error.message);
    }

    console.error("ADMIN_GROUPS_FAILED", {
      operation: event.arguments.operation,
      actorSub: caller.sub,
      error,
    });
    throw new Error("The operation could not be completed. The error has been logged.");
  }
};

/* -------------------------------------------------------------------------- */

async function listGroups(
  caller: ReturnType<typeof resolveCaller>,
): Promise<GroupAccessView[]> {
  const views = await Promise.all(
    activeClient.groups.map(async (group) => {
      const [memberCount, liveAccess] = await Promise.all([
        countMembers(group.id),
        readLiveAccess(group.id),
      ]);

      const configAccess = grantedBuckets(activeClient, group).map((g) => ({
        bucketId: g.bucket.id,
        mode: g.mode,
      }));

      // Live IAM is the truth, since it is what actually gates S3. Config is
      // shown as the baseline so an admin can see when the two have diverged.
      const effective = liveAccess ?? configAccess;

      return {
        id: group.id,
        label: group.label,
        description: group.description,
        isAdmin: group.isAdmin === true,
        memberCount,
        access: effective.map((entry) => ({
          bucketId: entry.bucketId,
          bucketLabel:
            activeClient.buckets.find((b) => b.id === entry.bucketId)?.label ??
            entry.bucketId,
          mode: entry.mode,
        })),
        divergedFromConfig: !sameAccess(effective, configAccess),
      } satisfies GroupAccessView;
    }),
  );

  await writeAuditEvent(data, activeClient.clientId, caller, {
    action: "GROUP_ACCESS_VIEWED",
    outcome: "SUCCESS",
  });

  return views;
}

async function setGroupAccess(
  groupId: string,
  access: readonly { bucketId: string; mode: AccessMode }[],
  caller: ReturnType<typeof resolveCaller>,
) {
  const roleName = ROLE_NAMES[groupId];
  if (!roleName) {
    throw new OperationError(`No IAM role is mapped for group "${groupId}".`);
  }

  const previous = await readLiveAccess(groupId);

  const policy = buildBucketPolicy(
    access.map((entry) => ({
      bucketName: activeClient.buckets.find((b) => b.id === entry.bucketId)!.bucketName,
      mode: entry.mode,
    })),
  );

  if (policy === null) {
    // No grants left: remove the inline policy rather than write an empty one,
    // which IAM rejects. The role keeps its permissions boundary, so it still
    // cannot reach anything.
    await iam.send(
      new DeleteRolePolicyCommand({
        RoleName: roleName,
        PolicyName: MANAGED_POLICY_NAME,
      }),
    );
  } else {
    await iam.send(
      new PutRolePolicyCommand({
        RoleName: roleName,
        PolicyName: MANAGED_POLICY_NAME,
        PolicyDocument: JSON.stringify(policy),
      }),
    );
  }

  await writeAuditEvent(data, activeClient.clientId, caller, {
    action: "GROUP_ACCESS_CHANGED",
    outcome: "SUCCESS",
    detail: {
      groupId,
      roleName,
      previous: previous ?? "(none — was using the deploy-time policy)",
      next: access,
    },
  });

  return { groupId, access };
}

/* -------------------------------------------------------------------------- */

/**
 * Reads the group's current access back out of IAM.
 *
 * Returns `null` when the portal has never written a policy for this group, in
 * which case the deploy-time policy from config is what applies.
 */
async function readLiveAccess(
  groupId: string,
): Promise<{ bucketId: string; mode: AccessMode }[] | null> {
  const roleName = ROLE_NAMES[groupId];
  if (!roleName) return null;

  try {
    const result = await iam.send(
      new GetRolePolicyCommand({
        RoleName: roleName,
        PolicyName: MANAGED_POLICY_NAME,
      }),
    );

    if (!result.PolicyDocument) return null;

    // IAM returns the document URL-encoded.
    const document = JSON.parse(decodeURIComponent(result.PolicyDocument)) as {
      Statement: { Sid?: string; Effect: string; Resource: string[] }[];
    };

    const readArns = document.Statement.find(
      (s) => s.Sid === "ReadGrantedObjects",
    )?.Resource;
    const uploadArns =
      document.Statement.find((s) => s.Sid === "UploadNewObjects")?.Resource ?? [];

    if (!readArns) return null;

    const uploadable = new Set(uploadArns.map(bucketNameFromArn));

    return readArns
      .map(bucketNameFromArn)
      .map((bucketName) => {
        const bucket = activeClient.buckets.find((b) => b.bucketName === bucketName);
        if (!bucket) return null;
        return {
          bucketId: bucket.id,
          mode: (uploadable.has(bucketName) ? "read-upload" : "read") as AccessMode,
        };
      })
      .filter((entry): entry is { bucketId: string; mode: AccessMode } => entry !== null);
  } catch (error) {
    if ((error as { name?: string }).name === "NoSuchEntityException") return null;
    throw error;
  }
}

function bucketNameFromArn(arn: string): string {
  return arn.replace(/^arn:aws:s3:::/, "").replace(/\/\*$/, "");
}

function sameAccess(
  a: readonly { bucketId: string; mode: AccessMode }[],
  b: readonly { bucketId: string; mode: AccessMode }[],
): boolean {
  if (a.length !== b.length) return false;
  const key = (entry: { bucketId: string; mode: AccessMode }) =>
    `${entry.bucketId}:${entry.mode}`;
  const setB = new Set(b.map(key));
  return a.every((entry) => setB.has(key(entry)));
}

async function countMembers(groupId: string): Promise<number> {
  let count = 0;
  let nextToken: string | undefined;

  do {
    const page = await cognito.send(
      new ListUsersInGroupCommand({
        UserPoolId: USER_POOL_ID,
        GroupName: groupId,
        Limit: 60,
        NextToken: nextToken,
      }),
    );
    count += page.Users?.length ?? 0;
    nextToken = page.NextToken;
  } while (nextToken);

  return count;
}
