import { activeClient } from "../../../config";
import type { AccessMode } from "../../../config/types";

/**
 * Request contracts for the `manageGroups` mutation.
 *
 * Note what is *not* accepted anywhere here: policy JSON. A caller may only
 * name a group, a bucket and a mode. The policy document is then generated by
 * `buildBucketPolicy`, which has no branch that can emit a destructive action.
 * This is what keeps runtime policy editing bounded — the caller chooses from
 * a closed set, rather than supplying IAM for us to apply.
 */

export class OperationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "OperationError";
  }
}

export interface GroupAccessView {
  readonly id: string;
  readonly label: string;
  readonly description: string;
  readonly isAdmin: boolean;
  readonly memberCount: number;
  readonly access: readonly {
    readonly bucketId: string;
    readonly bucketLabel: string;
    readonly mode: AccessMode;
  }[];
  /** True when the live IAM policy differs from what the config declares. */
  readonly divergedFromConfig: boolean;
}

export type ManageGroupsOperation =
  | { readonly operation: "listGroups" }
  | {
      readonly operation: "setGroupAccess";
      readonly groupId: string;
      readonly access: readonly { readonly bucketId: string; readonly mode: AccessMode }[];
    };

const VALID_MODES: readonly AccessMode[] = ["read", "read-upload"];

export function parseOperation(
  operation: string,
  payload: unknown,
): ManageGroupsOperation {
  const input = (payload ?? {}) as Record<string, unknown>;

  switch (operation) {
    case "listGroups":
      return { operation: "listGroups" };

    case "setGroupAccess": {
      const groupId = input.groupId;
      if (typeof groupId !== "string" || groupId === "") {
        throw new OperationError(`"groupId" is required.`);
      }

      const group = activeClient.groups.find((g) => g.id === groupId);
      if (!group) {
        throw new OperationError(
          `Unknown group "${groupId}". Groups are created by config change and ` +
            `deploy; see docs/decisions/group-management.md.`,
        );
      }

      if (!Array.isArray(input.access)) {
        throw new OperationError(`"access" must be an array of bucket grants.`);
      }

      const knownBuckets = new Set(activeClient.buckets.map((b) => b.id));
      const seen = new Set<string>();
      const access = input.access.map((entry) => {
        const record = (entry ?? {}) as Record<string, unknown>;
        const bucketId = record.bucketId;
        const mode = record.mode;

        if (typeof bucketId !== "string" || !knownBuckets.has(bucketId)) {
          throw new OperationError(
            `Unknown bucket "${String(bucketId)}". Valid buckets: ` +
              activeClient.buckets.map((b) => b.id).join(", "),
          );
        }
        if (typeof mode !== "string" || !VALID_MODES.includes(mode as AccessMode)) {
          throw new OperationError(
            `Invalid access mode "${String(mode)}" for bucket "${bucketId}". ` +
              `Valid modes: ${VALID_MODES.join(", ")}.`,
          );
        }
        if (seen.has(bucketId)) {
          throw new OperationError(`Bucket "${bucketId}" appears twice.`);
        }
        seen.add(bucketId);

        return { bucketId, mode: mode as AccessMode };
      });

      // The admin group is the portal's way back in. Narrowing its reach from
      // the UI could strand an administrator outside a bucket with no in-app
      // route to restore it.
      if (group.isAdmin && access.length < activeClient.buckets.length) {
        throw new OperationError(
          `The administrator group must retain access to every bucket. ` +
            `Change its definition in the client config if that is genuinely intended.`,
        );
      }

      return { operation: "setGroupAccess", groupId, access };
    }

    default:
      throw new OperationError(`Unknown operation "${operation}".`);
  }
}

/** Inline policy name used for the portal-managed access policy on a group role. */
export const MANAGED_POLICY_NAME = "portal-bucket-access";
