import { defineFunction } from "@aws-amplify/backend";

/**
 * Admin-only group management: view every group's bucket access, and change it
 * at runtime without opening the AWS console.
 *
 * ## How runtime IAM editing is kept safe
 *
 * This function holds `iam:PutRolePolicy` over the Cognito group roles, which
 * is genuinely the privilege an attacker would want. Four things bound it:
 *
 *  1. **Resource scoping** — the grant in `backend.ts` names only the group
 *     role ARNs. It cannot reach its own execution role, the admin role, or
 *     anything else in the account.
 *  2. **No policy JSON from callers** — the mutation accepts only
 *     `(groupId, bucketId, mode)` tuples drawn from the client config. The
 *     document is generated by `buildBucketPolicy`, which has no branch that
 *     emits a destructive action.
 *  3. **Permissions boundary** — every group role carries a boundary capping
 *     it at the configured buckets with destructive and IAM actions denied.
 *     A boundary is an intersection, so nothing written here can exceed it.
 *  4. **No attach, no create** — the grant excludes `iam:AttachRolePolicy`
 *     (which could bind AdministratorAccess), `iam:CreateRole` and
 *     `iam:PassRole`.
 *
 * ## What still requires a deploy
 *
 * Creating a *new* group. A new group needs a new IAM role, which means
 * `iam:CreateRole` and `iam:PassRole` — and those cannot be pre-scoped to a
 * role that does not exist yet, which would reopen the escalation path that
 * (1) and (4) close. New groups are therefore a client-config change and
 * deploy, which is reviewable and version-controlled. Editing the access of
 * an existing group, and moving users between groups, are both runtime
 * operations. See `docs/decisions/group-management.md`.
 */
export const adminGroupsFunction = defineFunction({
  name: "admin-groups",
  // An AppSync resolver lives with the API that invokes it; placing it
  // anywhere else creates a circular dependency between nested stacks.
  resourceGroupName: "data",
  entry: "./handler.ts",
  timeoutSeconds: 30,
  memoryMB: 256,
});
